  02-postgresql-setup[m
  03-basic-sql-queries[m
  04-aggregates-and-grouping[m
  05-update-and-delete[m
  06-sql-joins[m
  07-subqueries-and-views[m
  08-indexes-and-optimization[m
  09-functions-and-procedures[m
  backend102-health-endpoint[m
  backend102-start[m
  final-project[m
  last[m
  lesson-01-intro-to-db[m
* [32mmain[m
  project[m
  task-4[m
  task-5[m
  task-6[m
  task10[m
  task6[m
  task7[m
  task8[m
  task9[m
  user-management[m
